name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: erlang:${{matrix.otp}}
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: 
          - 22.2.6
          - 21.3.8.13
          - 20.3.8.25
          - 19.3.6.13
          - 18.3.4.11
    steps:
      - uses: actions/checkout@v2
      - run: rebar3 compile
        name: Compile
      - run: rebar3 do eunit, ct
        name: Test
