name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: erlang:${{matrix.otp}}
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: 
          - 22
          - 21
          - 20
          - 19
          - 18
    steps:
      - uses: actions/checkout@v2
      - run: rebar3 compile
        name: Compile
      - run: rebar3 do eunit, ct
        name: Test
