on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: erlang:${{matrix.otp}}
    name: OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: [22.0.7]
    steps:
      - uses: actions/checkout@v2
      - run: rebar3 compile
      - run: rebar3 do eunit, ct
